### ISSUE TITLE
Parliament2 svtyper bug?

### ISSUE THREAD

**Issue by pauline-ng** [gevro/five-dollar-genome-analysis-pipeline#1]
Hi @gevro ,

Apologies for contacting you this way, but Parliament2 isn't allowing issues to be opened.

You found a bug in Parliament2 with svtyper (#https://github.com/dnanexus/parliament2/issues/78 ). 

> 
> Another bug in parallelize_svtyper.sh:
> 
> `echo "svtyper -B $input_bam -i $directory/$i >> $directory/$i" >> $output.cmds`
> 
> svtyper is being run to take an input file and then output to the same input file. This does not work and leads to an empty output file. I'm not sure how svtyper ever worked with this script.

I'm running into this problem -- could you tell me what you did to fix this?

Appreciate all your bug fixes for Parliament 2. I've incorporated all of them!

Best,
Pauline

**Comment by gevro** [comment]
Hi Pauline, I actually don't remember the specific bug fixes I made, but you can pull my fixed docker here and see what I did: https://hub.docker.com/repository/docker/gevrony/parliament2-terra

**Comment by pauline-ng** [comment]
Thank you so much, I was able to pull your changes!

**Comment by warthmann** [comment]
Hello gevro, 
similarly, I apologise to be contacting you for parliament2, which should not be your job. Similarly I am trying to get it to work and experience the same issues as people before me including you. After trying all possible input modifications I could think of I arrived at your bugfixes and your gevrony/parliament2-terra image. In contrast to pauline-ng, I am not quite versed enough with docker to fix the original docker. I was hoping to use yours (gevrony/parliament2-terra) as a drop-in replacement. I pulled your image and I am trying to use it (using the same commandline as given for the original), but I am getting below error. Would you mind posting somewhere a commandline how to use it? I am on a  ubuntu workstation.

~/data/dnanexus$ docker run -v /home/norman/data/dnanexus/testin/:/home/dnanexus/in -v /home/norman/data/dnanexus/testout/:/home/dnanexus/out gevrony/parliament2-terra:latest --bam input.bam --bai input.bam.bai -r ref_genome.fa.gz --breakdancer --cnvnator --manta --genotype 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--bam": executable file not found in $PATH: unknown.
ERRO[0003] error waiting for container: context canceled 


thanks a lot for your help
best
Norman

**Comment by gevro** [comment]
It looks like your error has more to do with the docker environment rather than the container. However I don’t recommend to try and get this to work. You might be entering a quagmire. I suggest just using one or two independent SV callers.
